// 一年级下学期二类字字库
// 共4组，约200字

export const GROUPS = [
  {
    name: "自然·姓氏·动作",
    chars: [
      { char: "霜", pinyin: "shuāng", tone: 1 },
      { char: "吹", pinyin: "chuī", tone: 1 },
      { char: "落", pinyin: "luò", tone: 4 },
      { char: "降", pinyin: "jiàng", tone: 4 },
      { char: "飘", pinyin: "piāo", tone: 1 },
      { char: "游", pinyin: "yóu", tone: 2 },
      { char: "池", pinyin: "chí", tone: 2 },
      { char: "入", pinyin: "rù", tone: 4 },
      { char: "氏", pinyin: "shì", tone: 4 },
      { char: "什", pinyin: "shén", tone: 2 },
      { char: "李", pinyin: "lǐ", tone: 3 },
      { char: "张", pinyin: "zhāng", tone: 1 },
      { char: "弓", pinyin: "gōng", tone: 1 },
      { char: "古", pinyin: "gǔ", tone: 3 },
      { char: "胡", pinyin: "hú", tone: 2 },
      { char: "吴", pinyin: "wú", tone: 2 },
      { char: "言", pinyin: "yán", tone: 2 },
      { char: "孙", pinyin: "sūn", tone: 1 },
      { char: "河", pinyin: "hé", tone: 2 },
      { char: "晴", pinyin: "qíng", tone: 2 },
      { char: "眼", pinyin: "yǎn", tone: 3 },
      { char: "睛", pinyin: "jīng", tone: 1 },
      { char: "保", pinyin: "bǎo", tone: 3 },
      { char: "护", pinyin: "hù", tone: 4 },
      { char: "苗", pinyin: "miáo", tone: 2 },
      { char: "吃", pinyin: "chī", tone: 1 },
      { char: "事", pinyin: "shì", tone: 4 },
      { char: "情", pinyin: "qíng", tone: 2 },
      { char: "请", pinyin: "qǐng", tone: 3 },
      { char: "让", pinyin: "ràng", tone: 4 },
      { char: "猜", pinyin: "cāi", tone: 1 },
      { char: "边", pinyin: "biān", tone: 1 },
      { char: "凉", pinyin: "liáng", tone: 2 },
      { char: "喜", pinyin: "xǐ", tone: 3 },
      { char: "欢", pinyin: "huān", tone: 1 },
      { char: "时", pinyin: "shí", tone: 2 },
      { char: "怕", pinyin: "pà", tone: 4 },
      { char: "攻", pinyin: "gōng", tone: 1 },
      { char: "令", pinyin: "lìng", tone: 4 },
      { char: "感", pinyin: "gǎn", tone: 3 },
      { char: "动", pinyin: "dòng", tone: 4 },
      { char: "万", pinyin: "wàn", tone: 4 },
      { char: "无", pinyin: "wú", tone: 2 },
      { char: "识", pinyin: "shí", tone: 2 },
      { char: "组", pinyin: "zǔ", tone: 3 },
      { char: "计", pinyin: "jì", tone: 4 },
      { char: "算", pinyin: "suàn", tone: 4 },
      { char: "减", pinyin: "jiǎn", tone: 3 },
      { char: "式", pinyin: "shì", tone: 4 },
      { char: "图", pinyin: "tú", tone: 2 },
      { char: "形", pinyin: "xíng", tone: 2 },
      { char: "卡", pinyin: "kǎ", tone: 3 },
      { char: "合", pinyin: "hé", tone: 2 },
      { char: "唱", pinyin: "chàng", tone: 4 },
      { char: "团", pinyin: "tuán", tone: 2 },
    ]
  },
  {
    name: "爱国·家乡",
    chars: [
      { char: "热", pinyin: "rè", tone: 4 },
      { char: "爱", pinyin: "ài", tone: 4 },
      { char: "共", pinyin: "gòng", tone: 4 },
      { char: "产", pinyin: "chǎn", tone: 3 },
      { char: "党", pinyin: "dǎng", tone: 3 },
      { char: "太", pinyin: "tài", tone: 4 },
      { char: "阳", pinyin: "yáng", tone: 2 },
      { char: "光", pinyin: "guāng", tone: 1 },
      { char: "怀", pinyin: "huái", tone: 2 },
      { char: "抱", pinyin: "bào", tone: 4 },
      { char: "幸", pinyin: "xìng", tone: 4 },
      { char: "福", pinyin: "fú", tone: 2 },
      { char: "成", pinyin: "chéng", tone: 2 },
      { char: "井", pinyin: "jǐng", tone: 3 },
      { char: "城", pinyin: "chéng", tone: 2 },
      { char: "村", pinyin: "cūn", tone: 1 },
      { char: "毛", pinyin: "máo", tone: 2 },
      { char: "主", pinyin: "zhǔ", tone: 3 },
      { char: "席", pinyin: "xí", tone: 2 },
      { char: "住", pinyin: "zhù", tone: 4 },
      { char: "乡", pinyin: "xiāng", tone: 1 },
      { char: "亲", pinyin: "qīn", tone: 1 },
      { char: "战", pinyin: "zhàn", tone: 4 },
      { char: "士", pinyin: "shì", tone: 4 },
      { char: "想", pinyin: "xiǎng", tone: 3 },
      { char: "念", pinyin: "niàn", tone: 4 },
      { char: "告", pinyin: "gào", tone: 4 },
      { char: "诉", pinyin: "sù", tone: 4 },
      { char: "走", pinyin: "zǒu", tone: 3 },
      { char: "京", pinyin: "jīng", tone: 1 },
      { char: "座", pinyin: "zuò", tone: 4 },
      { char: "安", pinyin: "ān", tone: 1 },
      { char: "广", pinyin: "guǎng", tone: 3 },
      { char: "场", pinyin: "chǎng", tone: 3 },
      { char: "非", pinyin: "fēi", tone: 1 },
      { char: "宽", pinyin: "kuān", tone: 1 },
      { char: "丽", pinyin: "lì", tone: 4 },
      { char: "洁", pinyin: "jié", tone: 2 },
      { char: "认", pinyin: "rèn", tone: 4 },
      { char: "连", pinyin: "lián", tone: 2 },
      { char: "选", pinyin: "xuǎn", tone: 3 },
      { char: "圈", pinyin: "quān", tone: 1 },
      { char: "涂", pinyin: "tú", tone: 2 },
      { char: "填", pinyin: "tián", tone: 2 },
      { char: "试", pinyin: "shì", tone: 4 },
      { char: "练", pinyin: "liàn", tone: 4 },
    ]
  },
  {
    name: "校园·游戏·朋友",
    chars: [
      { char: "玩", pinyin: "wán", tone: 2 },
      { char: "得", pinyin: "dé", tone: 2 },
      { char: "急", pinyin: "jí", tone: 2 },
      { char: "直", pinyin: "zhí", tone: 2 },
      { char: "哭", pinyin: "kū", tone: 1 },
      { char: "跟", pinyin: "gēn", tone: 1 },
      { char: "忽", pinyin: "hū", tone: 1 },
      { char: "然", pinyin: "rán", tone: 2 },
      { char: "听", pinyin: "tīng", tone: 1 },
      { char: "喊", pinyin: "hǎn", tone: 3 },
      { char: "快", pinyin: "kuài", tone: 4 },
      { char: "己", pinyin: "jǐ", tone: 3 },
      { char: "背", pinyin: "bèi", tone: 4 },
      { char: "只", pinyin: "zhī", tone: 1 },
      { char: "很", pinyin: "hěn", tone: 3 },
      { char: "孤", pinyin: "gū", tone: 1 },
      { char: "单", pinyin: "dān", tone: 1 },
      { char: "种", pinyin: "zhǒng", tone: 3 },
      { char: "每", pinyin: "měi", tone: 3 },
      { char: "都", pinyin: "dōu", tone: 1 },
      { char: "邻", pinyin: "lín", tone: 2 },
      { char: "居", pinyin: "jū", tone: 1 },
      { char: "叫", pinyin: "jiào", tone: 4 },
      { char: "招", pinyin: "zhāo", tone: 1 },
      { char: "呼", pinyin: "hū", tone: 1 },
      { char: "乐", pinyin: "lè", tone: 4 },
      { char: "怎", pinyin: "zěn", tone: 3 },
      { char: "独", pinyin: "dú", tone: 2 },
      { char: "跳", pinyin: "tiào", tone: 4 },
      { char: "绳", pinyin: "shéng", tone: 2 },
      { char: "当", pinyin: "dāng", tone: 1 },
      { char: "还", pinyin: "hái", tone: 2 },
      { char: "羽", pinyin: "yǔ", tone: 3 },
      { char: "球", pinyin: "qiú", tone: 2 },
      { char: "劲", pinyin: "jìn", tone: 4 },
      { char: "轮", pinyin: "lún", tone: 2 },
      { char: "排", pinyin: "pái", tone: 2 },
      { char: "母", pinyin: "mǔ", tone: 3 },
      { char: "页", pinyin: "yè", tone: 4 },
      { char: "止", pinyin: "zhǐ", tone: 3 },
      { char: "斤", pinyin: "jīn", tone: 1 },
      { char: "寸", pinyin: "cùn", tone: 4 },
      { char: "丁", pinyin: "dīng", tone: 1 },
      { char: "千", pinyin: "qiān", tone: 1 },
      { char: "全", pinyin: "quán", tone: 2 },
      { char: "元", pinyin: "yuán", tone: 2 },
    ]
  },
  {
    name: "日常·节日·生活",
    chars: [
      { char: "静", pinyin: "jìng", tone: 4 },
      { char: "思", pinyin: "sī", tone: 1 },
      { char: "床", pinyin: "chuáng", tone: 2 },
      { char: "疑", pinyin: "yí", tone: 2 },
      { char: "举", pinyin: "jǔ", tone: 3 },
      { char: "望", pinyin: "wàng", tone: 4 },
      { char: "低", pinyin: "dī", tone: 1 },
      { char: "故", pinyin: "gù", tone: 4 },
      { char: "胆", pinyin: "dǎn", tone: 3 },
      { char: "敢", pinyin: "gǎn", tone: 3 },
      { char: "勇", pinyin: "yǒng", tone: 3 },
      { char: "讲", pinyin: "jiǎng", tone: 3 },
      { char: "窗", pinyin: "chuāng", tone: 1 },
      { char: "乱", pinyin: "luàn", tone: 4 },
      { char: "拉", pinyin: "lā", tone: 1 },
      { char: "样", pinyin: "yàng", tone: 4 },
      { char: "笑", pinyin: "xiào", tone: 4 },
      { char: "再", pinyin: "zài", tone: 4 },
      { char: "睡", pinyin: "shuì", tone: 4 },
      { char: "觉", pinyin: "jiào", tone: 4 },
      { char: "端", pinyin: "duān", tone: 1 },
      { char: "粽", pinyin: "zòng", tone: 4 },
      { char: "节", pinyin: "jié", tone: 2 },
      { char: "总", pinyin: "zǒng", tone: 3 },
      { char: "煮", pinyin: "zhǔ", tone: 3 },
      { char: "盼", pinyin: "pàn", tone: 4 },
      { char: "米", pinyin: "mǐ", tone: 3 },
      { char: "枣", pinyin: "zǎo", tone: 3 },
      { char: "甜", pinyin: "tián", tone: 2 },
      { char: "分", pinyin: "fēn", tone: 1 },
      { char: "鲜", pinyin: "xiān", tone: 1 },
      { char: "肉", pinyin: "ròu", tone: 4 },
      { char: "了", pinyin: "le", tone: 0 },
      { char: "册", pinyin: "cè", tone: 4 },
      { char: "支", pinyin: "zhī", tone: 1 },
      { char: "台", pinyin: "tái", tone: 2 },
      { char: "电", pinyin: "diàn", tone: 4 },
      { char: "视", pinyin: "shì", tone: 4 },
      { char: "部", pinyin: "bù", tone: 4 },
      { char: "机", pinyin: "jī", tone: 1 },
      { char: "衣", pinyin: "yī", tone: 1 },
      { char: "裤", pinyin: "kù", tone: 4 },
      { char: "被", pinyin: "bèi", tone: 4 },
    ]
  }
];

// 展开所有字为扁平数组，附带groupId
export function getAllChars() {
  const all = [];
  GROUPS.forEach((group, gi) => {
    group.chars.forEach((c, ci) => {
      all.push({ ...c, id: `${gi}-${ci}`, groupId: gi, groupName: group.name });
    });
  });
  return all;
}
