// 一年级下学期二类字字库
// 共412字，35组

export const GROUPS = [
  {
    name: '第1组',
    chars: [
      { char: '霜', pinyin: 'shuang', phrase: '霜降' },
      { char: '吹', pinyin: 'chui', phrase: '吹风' },
      { char: '落', pinyin: 'luo', phrase: '落下' },
      { char: '降', pinyin: 'jiang', phrase: '降落' },
      { char: '飘', pinyin: 'piao', phrase: '飘扬' },
      { char: '游', pinyin: 'you', phrase: '游泳' },
      { char: '池', pinyin: 'chi', phrase: '池塘' },
      { char: '入', pinyin: 'ru', phrase: '进入' },
      { char: '氏', pinyin: 'shi', phrase: '姓氏' },
      { char: '什', pinyin: 'shen', phrase: '什么' },
      { char: '李', pinyin: 'li', phrase: '李子' },
      { char: '张', pinyin: 'zhang', phrase: '张开' }
    ]
  },
  {
    name: '第2组',
    chars: [
      { char: '弓', pinyin: 'gong', phrase: '弓箭' },
      { char: '古', pinyin: 'gu', phrase: '古代' },
      { char: '胡', pinyin: 'hu', phrase: '胡子' },
      { char: '吴', pinyin: 'wu', phrase: '吴国' },
      { char: '言', pinyin: 'yan', phrase: '语言' },
      { char: '孙', pinyin: 'sun', phrase: '孙子' },
      { char: '河', pinyin: 'he', phrase: '河水' },
      { char: '晴', pinyin: 'qing', phrase: '晴天' },
      { char: '眼', pinyin: 'yan', phrase: '眼睛' },
      { char: '睛', pinyin: 'jing', phrase: '定睛' },
      { char: '保', pinyin: 'bao', phrase: '保护' },
      { char: '护', pinyin: 'hu', phrase: '护士' }
    ]
  },
  {
    name: '第3组',
    chars: [
      { char: '苗', pinyin: 'miao', phrase: '禾苗' },
      { char: '吃', pinyin: 'chi', phrase: '吃饭' },
      { char: '事', pinyin: 'shi', phrase: '事情' },
      { char: '情', pinyin: 'qing', phrase: '心情' },
      { char: '请', pinyin: 'qing', phrase: '请问' },
      { char: '让', pinyin: 'rang', phrase: '让开' },
      { char: '猜', pinyin: 'cai', phrase: '猜谜' },
      { char: '边', pinyin: 'bian', phrase: '一边' },
      { char: '凉', pinyin: 'liang', phrase: '凉快' },
      { char: '喜', pinyin: 'xi', phrase: '喜欢' },
      { char: '欢', pinyin: 'huan', phrase: '欢乐' },
      { char: '时', pinyin: 'shi', phrase: '时间' }
    ]
  },
  {
    name: '第4组',
    chars: [
      { char: '怕', pinyin: 'pa', phrase: '害怕' },
      { char: '攻', pinyin: 'gong', phrase: '进攻' },
      { char: '令', pinyin: 'ling', phrase: '口令' },
      { char: '感', pinyin: 'gan', phrase: '感动' },
      { char: '动', pinyin: 'dong', phrase: '动作' },
      { char: '万', pinyin: 'wan', phrase: '万一' },
      { char: '无', pinyin: 'wu', phrase: '无人' },
      { char: '识', pinyin: 'shi', phrase: '认识' },
      { char: '组', pinyin: 'zu', phrase: '小组' },
      { char: '计', pinyin: 'ji', phrase: '计算' },
      { char: '算', pinyin: 'suan', phrase: '算术' },
      { char: '减', pinyin: 'jian', phrase: '减法' }
    ]
  },
  {
    name: '第5组',
    chars: [
      { char: '式', pinyin: 'shi', phrase: '公式' },
      { char: '图', pinyin: 'tu', phrase: '图画' },
      { char: '形', pinyin: 'xing', phrase: '形状' },
      { char: '卡', pinyin: 'ka', phrase: '卡片' },
      { char: '合', pinyin: 'he', phrase: '合作' },
      { char: '唱', pinyin: 'chang', phrase: '唱歌' },
      { char: '团', pinyin: 'tuan', phrase: '团长' },
      { char: '热', pinyin: 're', phrase: '热闹' },
      { char: '爱', pinyin: 'ai', phrase: '爱心' },
      { char: '共', pinyin: 'gong', phrase: '共同' },
      { char: '产', pinyin: 'chan', phrase: '生产' },
      { char: '党', pinyin: 'dang', phrase: '党员' }
    ]
  },
  {
    name: '第6组',
    chars: [
      { char: '太', pinyin: 'tai', phrase: '太阳' },
      { char: '阳', pinyin: 'yang', phrase: '阳光' },
      { char: '光', pinyin: 'guang', phrase: '光明' },
      { char: '怀', pinyin: 'huai', phrase: '怀抱' },
      { char: '抱', pinyin: 'bao', phrase: '拥抱' },
      { char: '幸', pinyin: 'xing', phrase: '幸福' },
      { char: '福', pinyin: 'fu', phrase: '福气' },
      { char: '成', pinyin: 'cheng', phrase: '成功' },
      { char: '井', pinyin: 'jing', phrase: '井水' },
      { char: '城', pinyin: 'cheng', phrase: '城市' },
      { char: '村', pinyin: 'cun', phrase: '村庄' },
      { char: '毛', pinyin: 'mao', phrase: '毛衣' }
    ]
  },
  {
    name: '第7组',
    chars: [
      { char: '主', pinyin: 'zhu', phrase: '主人' },
      { char: '席', pinyin: 'xi', phrase: '主席' },
      { char: '住', pinyin: 'zhu', phrase: '住下' },
      { char: '乡', pinyin: 'xiang', phrase: '家乡' },
      { char: '亲', pinyin: 'qin', phrase: '亲人' },
      { char: '战', pinyin: 'zhan', phrase: '战士' },
      { char: '士', pinyin: 'shi', phrase: '士兵' },
      { char: '想', pinyin: 'xiang', phrase: '想念' },
      { char: '念', pinyin: 'nian', phrase: '思念' },
      { char: '告', pinyin: 'gao', phrase: '告诉' },
      { char: '诉', pinyin: 'su', phrase: '诉说' },
      { char: '走', pinyin: 'zou', phrase: '走路' }
    ]
  },
  {
    name: '第8组',
    chars: [
      { char: '京', pinyin: 'jing', phrase: '北京' },
      { char: '座', pinyin: 'zuo', phrase: '座位' },
      { char: '安', pinyin: 'an', phrase: '安全' },
      { char: '广', pinyin: 'guang', phrase: '广大' },
      { char: '场', pinyin: 'chang', phrase: '广场' },
      { char: '非', pinyin: 'fei', phrase: '非常' },
      { char: '宽', pinyin: 'kuan', phrase: '宽广' },
      { char: '丽', pinyin: 'li', phrase: '美丽' },
      { char: '洁', pinyin: 'jie', phrase: '洁白' },
      { char: '认', pinyin: 'ren', phrase: '认真' },
      { char: '连', pinyin: 'lian', phrase: '连忙' },
      { char: '选', pinyin: 'xuan', phrase: '选择' }
    ]
  },
  {
    name: '第9组',
    chars: [
      { char: '圈', pinyin: 'quan', phrase: '圆圈' },
      { char: '涂', pinyin: 'tu', phrase: '涂色' },
      { char: '填', pinyin: 'tian', phrase: '填写' },
      { char: '试', pinyin: 'shi', phrase: '考试' },
      { char: '练', pinyin: 'lian', phrase: '练习' },
      { char: '玩', pinyin: 'wan', phrase: '玩耍' },
      { char: '得', pinyin: 'de', phrase: '得到' },
      { char: '急', pinyin: 'ji', phrase: '着急' },
      { char: '直', pinyin: 'zhi', phrase: '一直' },
      { char: '哭', pinyin: 'ku', phrase: '哭声' },
      { char: '跟', pinyin: 'gen', phrase: '跟着' },
      { char: '忽', pinyin: 'hu', phrase: '忽然' }
    ]
  },
  {
    name: '第10组',
    chars: [
      { char: '然', pinyin: 'ran', phrase: '然后' },
      { char: '听', pinyin: 'ting', phrase: '听见' },
      { char: '喊', pinyin: 'han', phrase: '喊叫' },
      { char: '快', pinyin: 'kuai', phrase: '快乐' },
      { char: '己', pinyin: 'ji', phrase: '自己' },
      { char: '背', pinyin: 'bei', phrase: '背包' },
      { char: '只', pinyin: 'zhi', phrase: '只有' },
      { char: '很', pinyin: 'hen', phrase: '很多' },
      { char: '孤', pinyin: 'gu', phrase: '孤单' },
      { char: '单', pinyin: 'dan', phrase: '单独' },
      { char: '种', pinyin: 'zhong', phrase: '种子' },
      { char: '每', pinyin: 'mei', phrase: '每天' }
    ]
  },
  {
    name: '第11组',
    chars: [
      { char: '都', pinyin: 'dou', phrase: '都是' },
      { char: '邻', pinyin: 'lin', phrase: '邻居' },
      { char: '居', pinyin: 'ju', phrase: '居住' },
      { char: '叫', pinyin: 'jiao', phrase: '叫声' },
      { char: '招', pinyin: 'zhao', phrase: '招手' },
      { char: '呼', pinyin: 'hu', phrase: '招呼' },
      { char: '乐', pinyin: 'le', phrase: '快乐' },
      { char: '怎', pinyin: 'zen', phrase: '怎么' },
      { char: '独', pinyin: 'du', phrase: '独自' },
      { char: '跳', pinyin: 'tiao', phrase: '跳高' },
      { char: '绳', pinyin: 'sheng', phrase: '绳子' },
      { char: '当', pinyin: 'dang', phrase: '当然' }
    ]
  },
  {
    name: '第12组',
    chars: [
      { char: '还', pinyin: 'hai', phrase: '还有' },
      { char: '羽', pinyin: 'yu', phrase: '羽毛' },
      { char: '球', pinyin: 'qiu', phrase: '皮球' },
      { char: '劲', pinyin: 'jin', phrase: '使劲' },
      { char: '轮', pinyin: 'lun', phrase: '车轮' },
      { char: '排', pinyin: 'pai', phrase: '排队' },
      { char: '母', pinyin: 'mu', phrase: '母亲' },
      { char: '页', pinyin: 'ye', phrase: '页面' },
      { char: '止', pinyin: 'zhi', phrase: '停止' },
      { char: '斤', pinyin: 'jin', phrase: '公斤' },
      { char: '寸', pinyin: 'cun', phrase: '尺寸' },
      { char: '丁', pinyin: 'ding', phrase: '园丁' }
    ]
  },
  {
    name: '第13组',
    chars: [
      { char: '千', pinyin: 'qian', phrase: '千万' },
      { char: '全', pinyin: 'quan', phrase: '全部' },
      { char: '元', pinyin: 'yuan', phrase: '元旦' },
      { char: '静', pinyin: 'jing', phrase: '安静' },
      { char: '思', pinyin: 'si', phrase: '思念' },
      { char: '床', pinyin: 'chuang', phrase: '床头' },
      { char: '疑', pinyin: 'yi', phrase: '怀疑' },
      { char: '举', pinyin: 'ju', phrase: '举手' },
      { char: '望', pinyin: 'wang', phrase: '看望' },
      { char: '低', pinyin: 'di', phrase: '低头' },
      { char: '故', pinyin: 'gu', phrase: '故乡' },
      { char: '胆', pinyin: 'dan', phrase: '胆子' }
    ]
  },
  {
    name: '第14组',
    chars: [
      { char: '敢', pinyin: 'gan', phrase: '勇敢' },
      { char: '勇', pinyin: 'yong', phrase: '勇气' },
      { char: '讲', pinyin: 'jiang', phrase: '讲话' },
      { char: '窗', pinyin: 'chuang', phrase: '窗户' },
      { char: '乱', pinyin: 'luan', phrase: '乱说' },
      { char: '拉', pinyin: 'la', phrase: '拉手' },
      { char: '样', pinyin: 'yang', phrase: '样子' },
      { char: '笑', pinyin: 'xiao', phrase: '笑声' },
      { char: '再', pinyin: 'zai', phrase: '再见' },
      { char: '睡', pinyin: 'shui', phrase: '睡觉' },
      { char: '觉', pinyin: 'jue', phrase: '午觉' },
      { char: '端', pinyin: 'duan', phrase: '端正' }
    ]
  },
  {
    name: '第15组',
    chars: [
      { char: '粽', pinyin: 'zong', phrase: '粽子' },
      { char: '节', pinyin: 'jie', phrase: '节日' },
      { char: '总', pinyin: 'zong', phrase: '总是' },
      { char: '煮', pinyin: 'zhu', phrase: '煮饭' },
      { char: '盼', pinyin: 'pan', phrase: '盼望' },
      { char: '米', pinyin: 'mi', phrase: '大米' },
      { char: '枣', pinyin: 'zao', phrase: '红枣' },
      { char: '甜', pinyin: 'tian', phrase: '香甜' },
      { char: '分', pinyin: 'fen', phrase: '分开' },
      { char: '鲜', pinyin: 'xian', phrase: '新鲜' },
      { char: '肉', pinyin: 'rou', phrase: '牛肉' },
      { char: '了', pinyin: 'le', phrase: '好了' }
    ]
  },
  {
    name: '第16组',
    chars: [
      { char: '册', pinyin: 'ce', phrase: '画册' },
      { char: '支', pinyin: 'zhi', phrase: '一支' },
      { char: '台', pinyin: 'tai', phrase: '台风' },
      { char: '电', pinyin: 'dian', phrase: '电话' },
      { char: '视', pinyin: 'shi', phrase: '电视' },
      { char: '部', pinyin: 'bu', phrase: '部分' },
      { char: '机', pinyin: 'ji', phrase: '飞机' },
      { char: '衣', pinyin: 'yi', phrase: '衣服' },
      { char: '裤', pinyin: 'ku', phrase: '裤子' },
      { char: '物', pinyin: 'wu', phrase: '动物' },
      { char: '捉', pinyin: 'zhuo', phrase: '捉住' },
      { char: '迷', pinyin: 'mi', phrase: '迷路' }
    ]
  },
  {
    name: '第17组',
    chars: [
      { char: '藏', pinyin: 'cang', phrase: '捉迷藏' },
      { char: '造', pinyin: 'zao', phrase: '造句' },
      { char: '蚂', pinyin: 'ma', phrase: '蚂蚁' },
      { char: '蚁', pinyin: 'yi', phrase: '白蚁' },
      { char: '运', pinyin: 'yun', phrase: '运动' },
      { char: '食', pinyin: 'shi', phrase: '食物' },
      { char: '粮', pinyin: 'liang', phrase: '粮食' },
      { char: '房', pinyin: 'fang', phrase: '房子' },
      { char: '结', pinyin: 'jie', phrase: '结果' },
      { char: '网', pinyin: 'wang', phrase: '上网' },
      { char: '圆', pinyin: 'yuan', phrase: '圆形' },
      { char: '严', pinyin: 'yan', phrase: '严格' }
    ]
  },
  {
    name: '第18组',
    chars: [
      { char: '寒', pinyin: 'han', phrase: '寒冷' },
      { char: '酷', pinyin: 'ku', phrase: '酷热' },
      { char: '暑', pinyin: 'shu', phrase: '暑假' },
      { char: '暖', pinyin: 'nuan', phrase: '温暖' },
      { char: '晨', pinyin: 'chen', phrase: '早晨' },
      { char: '细', pinyin: 'xi', phrase: '细心' },
      { char: '朝', pinyin: 'chao', phrase: '朝阳' },
      { char: '霞', pinyin: 'xia', phrase: '晚霞' },
      { char: '夕', pinyin: 'xi', phrase: '夕阳' },
      { char: '杨', pinyin: 'yang', phrase: '杨树' },
      { char: '香', pinyin: 'xiang', phrase: '香气' },
      { char: '操', pinyin: 'cao', phrase: '操场' }
    ]
  },
  {
    name: '第19组',
    chars: [
      { char: '拔', pinyin: 'ba', phrase: '拔草' },
      { char: '拍', pinyin: 'pai', phrase: '拍手' },
      { char: '跑', pinyin: 'pao', phrase: '跑步' },
      { char: '踢', pinyin: 'ti', phrase: '踢球' },
      { char: '铃', pinyin: 'ling', phrase: '铃声' },
      { char: '真', pinyin: 'zhen', phrase: '真正' },
      { char: '闹', pinyin: 'nao', phrase: '热闹' },
      { char: '丢', pinyin: 'diu', phrase: '丢失' },
      { char: '沙', pinyin: 'sha', phrase: '沙子' },
      { char: '身', pinyin: 'shen', phrase: '身体' },
      { char: '体', pinyin: 'ti', phrase: '体育' },
      { char: '之', pinyin: 'zhi', phrase: '之后' }
    ]
  },
  {
    name: '第20组',
    chars: [
      { char: '初', pinyin: 'chu', phrase: '初一' },
      { char: '相', pinyin: 'xiang', phrase: '相信' },
      { char: '近', pinyin: 'jin', phrase: '远近' },
      { char: '习', pinyin: 'xi', phrase: '学习' },
      { char: '远', pinyin: 'yuan', phrase: '远方' },
      { char: '教', pinyin: 'jiao', phrase: '教师' },
      { char: '道', pinyin: 'dao', phrase: '道路' },
      { char: '专', pinyin: 'zhuan', phrase: '专心' },
      { char: '幼', pinyin: 'you', phrase: '幼儿' },
      { char: '玉', pinyin: 'yu', phrase: '玉米' },
      { char: '知', pinyin: 'zhi', phrase: '知道' },
      { char: '义', pinyin: 'yi', phrase: '意义' }
    ]
  },
  {
    name: '第21组',
    chars: [
      { char: '饭', pinyin: 'fan', phrase: '吃饭' },
      { char: '饱', pinyin: 'bao', phrase: '吃饱' },
      { char: '茶', pinyin: 'cha', phrase: '喝茶' },
      { char: '泡', pinyin: 'pao', phrase: '水泡' },
      { char: '轻', pinyin: 'qing', phrase: '轻轻' },
      { char: '穿', pinyin: 'chuan', phrase: '穿衣' },
      { char: '袍', pinyin: 'pao', phrase: '长袍' },
      { char: '鞭', pinyin: 'bian', phrase: '鞭子' },
      { char: '炮', pinyin: 'pao', phrase: '大炮' },
      { char: '诗', pinyin: 'shi', phrase: '诗人' },
      { char: '首', pinyin: 'shou', phrase: '首先' },
      { char: '偷', pinyin: 'tou', phrase: '小偷' }
    ]
  },
  {
    name: '第22组',
    chars: [
      { char: '浮', pinyin: 'fu', phrase: '漂浮' },
      { char: '萍', pinyin: 'ping', phrase: '浮萍' },
      { char: '泉', pinyin: 'quan', phrase: '泉水' },
      { char: '惜', pinyin: 'xi', phrase: '可惜' },
      { char: '照', pinyin: 'zhao', phrase: '照亮' },
      { char: '柔', pinyin: 'rou', phrase: '柔和' },
      { char: '荷', pinyin: 'he', phrase: '荷花' },
      { char: '露', pinyin: 'lu', phrase: '露水' },
      { char: '角', pinyin: 'jiao', phrase: '角落' },
      { char: '浪', pinyin: 'lang', phrase: '浪花' },
      { char: '迈', pinyin: 'mai', phrase: '迈步' },
      { char: '悄', pinyin: 'qiao', phrase: '悄悄' }
    ]
  },
  {
    name: '第23组',
    chars: [
      { char: '泪', pinyin: 'lei', phrase: '眼泪' },
      { char: '次', pinyin: 'ci', phrase: '一次' },
      { char: '给', pinyin: 'gei', phrase: '送给' },
      { char: '壳', pinyin: 'ke', phrase: '贝壳' },
      { char: '虾', pinyin: 'xia', phrase: '虾米' },
      { char: '装', pinyin: 'zhuang', phrase: '装备' },
      { char: '像', pinyin: 'xiang', phrase: '好像' },
      { char: '淘', pinyin: 'tao', phrase: '淘气' },
      { char: '娃', pinyin: 'wa', phrase: '娃娃' },
      { char: '珠', pinyin: 'zhu', phrase: '珍珠' },
      { char: '摇', pinyin: 'yao', phrase: '摇晃' },
      { char: '篮', pinyin: 'lan', phrase: '篮子' }
    ]
  },
  {
    name: '第24组',
    chars: [
      { char: '亮', pinyin: 'liang', phrase: '明亮' },
      { char: '晶', pinyin: 'jing', phrase: '晶莹' },
      { char: '停', pinyin: 'ting', phrase: '停止' },
      { char: '坪', pinyin: 'ping', phrase: '草坪' },
      { char: '展', pinyin: 'zhan', phrase: '展开' },
      { char: '透', pinyin: 'tou', phrase: '透明' },
      { char: '翅', pinyin: 'chi', phrase: '翅膀' },
      { char: '膀', pinyin: 'bang', phrase: '肩膀' },
      { char: '朵', pinyin: 'duo', phrase: '花朵' },
      { char: '要', pinyin: 'yao', phrase: '需要' },
      { char: '腰', pinyin: 'yao', phrase: '弯腰' },
      { char: '阴', pinyin: 'yin', phrase: '阴天' }
    ]
  },
  {
    name: '第25组',
    chars: [
      { char: '沉', pinyin: 'chen', phrase: '沉重' },
      { char: '呀', pinyin: 'ya', phrase: '好呀' },
      { char: '忙', pinyin: 'mang', phrase: '连忙' },
      { char: '呢', pinyin: 'ne', phrase: '人呢' },
      { char: '吗', pinyin: 'ma', phrase: '好吗' },
      { char: '面', pinyin: 'mian', phrase: '面子' },
      { char: '空', pinyin: 'kong', phrase: '天空' },
      { char: '闷', pinyin: 'men', phrase: '闷热' },
      { char: '吧', pinyin: 'ba', phrase: '好吧' },
      { char: '消', pinyin: 'xiao', phrase: '消失' },
      { char: '息', pinyin: 'xi', phrase: '休息' },
      { char: '棍', pinyin: 'gun', phrase: '木棍' }
    ]
  },
  {
    name: '第26组',
    chars: [
      { char: '豆', pinyin: 'dou', phrase: '豆子' },
      { char: '汤', pinyin: 'tang', phrase: '汤圆' },
      { char: '蚊', pinyin: 'wen', phrase: '蚊子' },
      { char: '扇', pinyin: 'shan', phrase: '扇子' },
      { char: '椅', pinyin: 'yi', phrase: '椅子' },
      { char: '牵', pinyin: 'qian', phrase: '牵手' },
      { char: '织', pinyin: 'zhi', phrase: '织布' },
      { char: '斗', pinyin: 'dou', phrase: '斗争' },
      { char: '具', pinyin: 'ju', phrase: '工具' },
      { char: '铅', pinyin: 'qian', phrase: '铅笔' },
      { char: '新', pinyin: 'xin', phrase: '新年' },
      { char: '平', pinyin: 'ping', phrase: '平安' }
    ]
  },
  {
    name: '第27组',
    chars: [
      { char: '盒', pinyin: 'he', phrase: '盒子' },
      { char: '些', pinyin: 'xie', phrase: '一些' },
      { char: '此', pinyin: 'ci', phrase: '此时' },
      { char: '仔', pinyin: 'zai', phrase: '仔细' },
      { char: '检', pinyin: 'jian', phrase: '检查' },
      { char: '查', pinyin: 'cha', phrase: '查找' },
      { char: '所', pinyin: 'suo', phrase: '所以' },
      { char: '伙', pinyin: 'huo', phrase: '伙伴' },
      { char: '伴', pinyin: 'ban', phrase: '同伴' },
      { char: '钟', pinyin: 'zhong', phrase: '时钟' },
      { char: '迟', pinyin: 'chi', phrase: '迟到' },
      { char: '灯', pinyin: 'deng', phrase: '灯光' }
    ]
  },
  {
    name: '第28组',
    chars: [
      { char: '等', pinyin: 'deng', phrase: '等待' },
      { char: '啊', pinyin: 'a', phrase: '好啊' },
      { char: '决', pinyin: 'jue', phrase: '决定' },
      { char: '定', pinyin: 'ding', phrase: '一定' },
      { char: '已', pinyin: 'yi', phrase: '已经' },
      { char: '经', pinyin: 'jing', phrase: '经过' },
      { char: '位', pinyin: 'wei', phrase: '位子' },
      { char: '表', pinyin: 'biao', phrase: '手表' },
      { char: '虎', pinyin: 'hu', phrase: '老虎' },
      { char: '熊', pinyin: 'xiong', phrase: '熊猫' },
      { char: '通', pinyin: 'tong', phrase: '通过' },
      { char: '注', pinyin: 'zhu', phrase: '注意' }
    ]
  },
  {
    name: '第29组',
    chars: [
      { char: '意', pinyin: 'yi', phrase: '意思' },
      { char: '遍', pinyin: 'bian', phrase: '一遍' },
      { char: '百', pinyin: 'bai', phrase: '一百' },
      { char: '为', pinyin: 'wei', phrase: '因为' },
      { char: '因', pinyin: 'yin', phrase: '原因' },
      { char: '舌', pinyin: 'she', phrase: '舌头' },
      { char: '理', pinyin: 'li', phrase: '道理' },
      { char: '忘', pinyin: 'wang', phrase: '忘记' },
      { char: '第', pinyin: 'di', phrase: '第一' },
      { char: '猴', pinyin: 'hou', phrase: '猴子' },
      { char: '块', pinyin: 'kuai', phrase: '一块' },
      { char: '兴', pinyin: 'xing', phrase: '高兴' }
    ]
  },
  {
    name: '第30组',
    chars: [
      { char: '掰', pinyin: 'bai', phrase: '掰开' },
      { char: '扛', pinyin: 'kang', phrase: '扛起' },
      { char: '往', pinyin: 'wang', phrase: '往常' },
      { char: '棵', pinyin: 'ke', phrase: '一棵' },
      { char: '满', pinyin: 'man', phrase: '满意' },
      { char: '扔', pinyin: 'reng', phrase: '扔掉' },
      { char: '摘', pinyin: 'zhai', phrase: '采摘' },
      { char: '捧', pinyin: 'peng', phrase: '捧着' },
      { char: '追', pinyin: 'zhui', phrase: '追赶' },
      { char: '刷', pinyin: 'shua', phrase: '刷牙' },
      { char: '梳', pinyin: 'shu', phrase: '梳子' },
      { char: '巾', pinyin: 'jin', phrase: '毛巾' }
    ]
  },
  {
    name: '第31组',
    chars: [
      { char: '皂', pinyin: 'zao', phrase: '香皂' },
      { char: '洗', pinyin: 'xi', phrase: '洗手' },
      { char: '澡', pinyin: 'zao', phrase: '洗澡' },
      { char: '脸', pinyin: 'lian', phrase: '洗脸' },
      { char: '盆', pinyin: 'pen', phrase: '盆子' },
      { char: '棉', pinyin: 'mian', phrase: '棉花' },
      { char: '姑', pinyin: 'gu', phrase: '姑姑' },
      { char: '娘', pinyin: 'niang', phrase: '姑娘' },
      { char: '病', pinyin: 'bing', phrase: '生病' },
      { char: '她', pinyin: 'ta', phrase: '她们' },
      { char: '治', pinyin: 'zhi', phrase: '治病' },
      { char: '燕', pinyin: 'yan', phrase: '燕子' }
    ]
  },
  {
    name: '第32组',
    chars: [
      { char: '帮', pinyin: 'bang', phrase: '帮忙' },
      { char: '害', pinyin: 'hai', phrase: '害怕' },
      { char: '别', pinyin: 'bie', phrase: '别人' },
      { char: '干', pinyin: 'gan', phrase: '干活' },
      { char: '惊', pinyin: 'jing', phrase: '惊奇' },
      { char: '奇', pinyin: 'qi', phrase: '奇怪' },
      { char: '咕', pinyin: 'gu', phrase: '咕噜' },
      { char: '咚', pinyin: 'dong', phrase: '叮咚' },
      { char: '熟', pinyin: 'shu', phrase: '熟悉' },
      { char: '掉', pinyin: 'diao', phrase: '掉下' },
      { char: '湖', pinyin: 'hu', phrase: '湖水' },
      { char: '吓', pinyin: 'xia', phrase: '吓人' }
    ]
  },
  {
    name: '第33组',
    chars: [
      { char: '啦', pinyin: 'la', phrase: '好啦' },
      { char: '鹿', pinyin: 'lu', phrase: '小鹿' },
      { char: '象', pinyin: 'xiang', phrase: '大象' },
      { char: '野', pinyin: 'ye', phrase: '田野' },
      { char: '拦', pinyin: 'lan', phrase: '拦住' },
      { char: '哪', pinyin: 'na', phrase: '哪里' },
      { char: '那', pinyin: 'na', phrase: '那里' },
      { char: '领', pinyin: 'ling', phrase: '带领' },
      { char: '壁', pinyin: 'bi', phrase: '墙壁' },
      { char: '借', pinyin: 'jie', phrase: '借书' },
      { char: '咬', pinyin: 'yao', phrase: '咬住' },
      { char: '难', pinyin: 'nan', phrase: '难过' }
    ]
  },
  {
    name: '第34组',
    chars: [
      { char: '爬', pinyin: 'pa', phrase: '爬山' },
      { char: '您', pinyin: 'nin', phrase: '您好' },
      { char: '拨', pinyin: 'bo', phrase: '拨动' },
      { char: '赶', pinyin: 'gan', phrase: '赶快' },
      { char: '摆', pinyin: 'bai', phrase: '摆动' },
      { char: '过', pinyin: 'guo', phrase: '过去' },
      { char: '孩', pinyin: 'hai', phrase: '孩子' },
      { char: '转', pinyin: 'zhuan', phrase: '转动' },
      { char: '吵', pinyin: 'chao', phrase: '吵闹' },
      { char: '现', pinyin: 'xian', phrase: '现在' },
      { char: '顶', pinyin: 'ding', phrase: '头顶' },
      { char: '胖', pinyin: 'pang', phrase: '胖子' }
    ]
  },
  {
    name: '第35组',
    chars: [
      { char: '票', pinyin: 'piao', phrase: '车票' },
      { char: '户', pinyin: 'hu', phrase: '户口' },
      { char: '交', pinyin: 'jiao', phrase: '交通' },
      { char: '父', pinyin: 'fu', phrase: '父亲' }
    ]
  },
];
// phraseMap for quick lookup
export const phraseMap = {
  "霜": "霜降",
  "吹": "吹风",
  "落": "落下",
  "降": "降落",
  "飘": "飘扬",
  "游": "游泳",
  "池": "池塘",
  "入": "进入",
  "氏": "姓氏",
  "什": "什么",
  "李": "李子",
  "张": "张开",
  "弓": "弓箭",
  "古": "古代",
  "胡": "胡子",
  "吴": "吴国",
  "言": "语言",
  "孙": "孙子",
  "河": "河水",
  "晴": "晴天",
  "眼": "眼睛",
  "睛": "定睛",
  "保": "保护",
  "护": "护士",
  "苗": "禾苗",
  "吃": "吃饭",
  "事": "事情",
  "情": "心情",
  "请": "请问",
  "让": "让开",
  "猜": "猜谜",
  "边": "一边",
  "凉": "凉快",
  "喜": "喜欢",
  "欢": "欢乐",
  "时": "时间",
  "怕": "害怕",
  "攻": "进攻",
  "令": "口令",
  "感": "感动",
  "动": "动作",
  "万": "万一",
  "无": "无人",
  "识": "认识",
  "组": "小组",
  "计": "计算",
  "算": "算术",
  "减": "减法",
  "式": "公式",
  "图": "图画",
  "形": "形状",
  "卡": "卡片",
  "合": "合作",
  "唱": "唱歌",
  "团": "团长",
  "热": "热闹",
  "爱": "爱心",
  "共": "共同",
  "产": "生产",
  "党": "党员",
  "太": "太阳",
  "阳": "阳光",
  "光": "光明",
  "怀": "怀抱",
  "抱": "拥抱",
  "幸": "幸福",
  "福": "福气",
  "成": "成功",
  "井": "井水",
  "城": "城市",
  "村": "村庄",
  "毛": "毛衣",
  "主": "主人",
  "席": "主席",
  "住": "住下",
  "乡": "家乡",
  "亲": "亲人",
  "战": "战士",
  "士": "士兵",
  "想": "想念",
  "念": "思念",
  "告": "告诉",
  "诉": "诉说",
  "走": "走路",
  "京": "北京",
  "座": "座位",
  "安": "安全",
  "广": "广大",
  "场": "广场",
  "非": "非常",
  "宽": "宽广",
  "丽": "美丽",
  "洁": "洁白",
  "认": "认真",
  "连": "连忙",
  "选": "选择",
  "圈": "圆圈",
  "涂": "涂色",
  "填": "填写",
  "试": "考试",
  "练": "练习",
  "玩": "玩耍",
  "得": "得到",
  "急": "着急",
  "直": "一直",
  "哭": "哭声",
  "跟": "跟着",
  "忽": "忽然",
  "然": "然后",
  "听": "听见",
  "喊": "喊叫",
  "快": "快乐",
  "己": "自己",
  "背": "背包",
  "只": "只有",
  "很": "很多",
  "孤": "孤单",
  "单": "单独",
  "种": "种子",
  "每": "每天",
  "都": "都是",
  "邻": "邻居",
  "居": "居住",
  "叫": "叫声",
  "招": "招手",
  "呼": "招呼",
  "乐": "快乐",
  "怎": "怎么",
  "独": "独自",
  "跳": "跳高",
  "绳": "绳子",
  "当": "当然",
  "还": "还有",
  "羽": "羽毛",
  "球": "皮球",
  "劲": "使劲",
  "轮": "车轮",
  "排": "排队",
  "母": "母亲",
  "页": "页面",
  "止": "停止",
  "斤": "公斤",
  "寸": "尺寸",
  "丁": "园丁",
  "千": "千万",
  "全": "全部",
  "元": "元旦",
  "静": "安静",
  "思": "思念",
  "床": "床头",
  "疑": "怀疑",
  "举": "举手",
  "望": "看望",
  "低": "低头",
  "故": "故乡",
  "胆": "胆子",
  "敢": "勇敢",
  "勇": "勇气",
  "讲": "讲话",
  "窗": "窗户",
  "乱": "乱说",
  "拉": "拉手",
  "样": "样子",
  "笑": "笑声",
  "再": "再见",
  "睡": "睡觉",
  "觉": "午觉",
  "端": "端正",
  "粽": "粽子",
  "节": "节日",
  "总": "总是",
  "煮": "煮饭",
  "盼": "盼望",
  "米": "大米",
  "枣": "红枣",
  "甜": "香甜",
  "分": "分开",
  "鲜": "新鲜",
  "肉": "牛肉",
  "了": "好了",
  "册": "画册",
  "支": "一支",
  "台": "台风",
  "电": "电话",
  "视": "电视",
  "部": "部分",
  "机": "飞机",
  "衣": "衣服",
  "裤": "裤子",
  "物": "动物",
  "捉": "捉住",
  "迷": "迷路",
  "藏": "捉迷藏",
  "造": "造句",
  "蚂": "蚂蚁",
  "蚁": "白蚁",
  "运": "运动",
  "食": "食物",
  "粮": "粮食",
  "房": "房子",
  "结": "结果",
  "网": "上网",
  "圆": "圆形",
  "严": "严格",
  "寒": "寒冷",
  "酷": "酷热",
  "暑": "暑假",
  "暖": "温暖",
  "晨": "早晨",
  "细": "细心",
  "朝": "朝阳",
  "霞": "晚霞",
  "夕": "夕阳",
  "杨": "杨树",
  "香": "香气",
  "操": "操场",
  "拔": "拔草",
  "拍": "拍手",
  "跑": "跑步",
  "踢": "踢球",
  "铃": "铃声",
  "真": "真正",
  "闹": "热闹",
  "丢": "丢失",
  "沙": "沙子",
  "身": "身体",
  "体": "体育",
  "之": "之后",
  "初": "初一",
  "相": "相信",
  "近": "远近",
  "习": "学习",
  "远": "远方",
  "教": "教师",
  "道": "道路",
  "专": "专心",
  "幼": "幼儿",
  "玉": "玉米",
  "知": "知道",
  "义": "意义",
  "饭": "吃饭",
  "饱": "吃饱",
  "茶": "喝茶",
  "泡": "水泡",
  "轻": "轻轻",
  "穿": "穿衣",
  "袍": "长袍",
  "鞭": "鞭子",
  "炮": "大炮",
  "诗": "诗人",
  "首": "首先",
  "偷": "小偷",
  "浮": "漂浮",
  "萍": "浮萍",
  "泉": "泉水",
  "惜": "可惜",
  "照": "照亮",
  "柔": "柔和",
  "荷": "荷花",
  "露": "露水",
  "角": "角落",
  "浪": "浪花",
  "迈": "迈步",
  "悄": "悄悄",
  "泪": "眼泪",
  "次": "一次",
  "给": "送给",
  "壳": "贝壳",
  "虾": "虾米",
  "装": "装备",
  "像": "好像",
  "淘": "淘气",
  "娃": "娃娃",
  "珠": "珍珠",
  "摇": "摇晃",
  "篮": "篮子",
  "亮": "明亮",
  "晶": "晶莹",
  "停": "停止",
  "坪": "草坪",
  "展": "展开",
  "透": "透明",
  "翅": "翅膀",
  "膀": "肩膀",
  "朵": "花朵",
  "要": "需要",
  "腰": "弯腰",
  "阴": "阴天",
  "沉": "沉重",
  "呀": "好呀",
  "忙": "连忙",
  "呢": "人呢",
  "吗": "好吗",
  "面": "面子",
  "空": "天空",
  "闷": "闷热",
  "吧": "好吧",
  "消": "消失",
  "息": "休息",
  "棍": "木棍",
  "豆": "豆子",
  "汤": "汤圆",
  "蚊": "蚊子",
  "扇": "扇子",
  "椅": "椅子",
  "牵": "牵手",
  "织": "织布",
  "斗": "斗争",
  "具": "工具",
  "铅": "铅笔",
  "新": "新年",
  "平": "平安",
  "盒": "盒子",
  "些": "一些",
  "此": "此时",
  "仔": "仔细",
  "检": "检查",
  "查": "查找",
  "所": "所以",
  "伙": "伙伴",
  "伴": "同伴",
  "钟": "时钟",
  "迟": "迟到",
  "灯": "灯光",
  "等": "等待",
  "啊": "好啊",
  "决": "决定",
  "定": "一定",
  "已": "已经",
  "经": "经过",
  "位": "位子",
  "表": "手表",
  "虎": "老虎",
  "熊": "熊猫",
  "通": "通过",
  "注": "注意",
  "意": "意思",
  "遍": "一遍",
  "百": "一百",
  "为": "因为",
  "因": "原因",
  "舌": "舌头",
  "理": "道理",
  "忘": "忘记",
  "第": "第一",
  "猴": "猴子",
  "块": "一块",
  "兴": "高兴",
  "掰": "掰开",
  "扛": "扛起",
  "往": "往常",
  "棵": "一棵",
  "满": "满意",
  "扔": "扔掉",
  "摘": "采摘",
  "捧": "捧着",
  "追": "追赶",
  "刷": "刷牙",
  "梳": "梳子",
  "巾": "毛巾",
  "皂": "香皂",
  "洗": "洗手",
  "澡": "洗澡",
  "脸": "洗脸",
  "盆": "盆子",
  "棉": "棉花",
  "姑": "姑姑",
  "娘": "姑娘",
  "病": "生病",
  "她": "她们",
  "治": "治病",
  "燕": "燕子",
  "帮": "帮忙",
  "害": "害怕",
  "别": "别人",
  "干": "干活",
  "惊": "惊奇",
  "奇": "奇怪",
  "咕": "咕噜",
  "咚": "叮咚",
  "熟": "熟悉",
  "掉": "掉下",
  "湖": "湖水",
  "吓": "吓人",
  "啦": "好啦",
  "鹿": "小鹿",
  "象": "大象",
  "野": "田野",
  "拦": "拦住",
  "哪": "哪里",
  "那": "那里",
  "领": "带领",
  "壁": "墙壁",
  "借": "借书",
  "咬": "咬住",
  "难": "难过",
  "爬": "爬山",
  "您": "您好",
  "拨": "拨动",
  "赶": "赶快",
  "摆": "摆动",
  "过": "过去",
  "孩": "孩子",
  "转": "转动",
  "吵": "吵闹",
  "现": "现在",
  "顶": "头顶",
  "胖": "胖子",
  "票": "车票",
  "户": "户口",
  "交": "交通",
  "父": "父亲"
};
// pinyinMap
export const pinyinMap = {
  "霜": "shuang",
  "吹": "chui",
  "落": "luo",
  "降": "jiang",
  "飘": "piao",
  "游": "you",
  "池": "chi",
  "入": "ru",
  "氏": "shi",
  "什": "shen",
  "李": "li",
  "张": "zhang",
  "弓": "gong",
  "古": "gu",
  "胡": "hu",
  "吴": "wu",
  "言": "yan",
  "孙": "sun",
  "河": "he",
  "晴": "qing",
  "眼": "yan",
  "睛": "jing",
  "保": "bao",
  "护": "hu",
  "苗": "miao",
  "吃": "chi",
  "事": "shi",
  "情": "qing",
  "请": "qing",
  "让": "rang",
  "猜": "cai",
  "边": "bian",
  "凉": "liang",
  "喜": "xi",
  "欢": "huan",
  "时": "shi",
  "怕": "pa",
  "攻": "gong",
  "令": "ling",
  "感": "gan",
  "动": "dong",
  "万": "wan",
  "无": "wu",
  "识": "shi",
  "组": "zu",
  "计": "ji",
  "算": "suan",
  "减": "jian",
  "式": "shi",
  "图": "tu",
  "形": "xing",
  "卡": "ka",
  "合": "he",
  "唱": "chang",
  "团": "tuan",
  "热": "re",
  "爱": "ai",
  "共": "gong",
  "产": "chan",
  "党": "dang",
  "太": "tai",
  "阳": "yang",
  "光": "guang",
  "怀": "huai",
  "抱": "bao",
  "幸": "xing",
  "福": "fu",
  "成": "cheng",
  "井": "jing",
  "城": "cheng",
  "村": "cun",
  "毛": "mao",
  "主": "zhu",
  "席": "xi",
  "住": "zhu",
  "乡": "xiang",
  "亲": "qin",
  "战": "zhan",
  "士": "shi",
  "想": "xiang",
  "念": "nian",
  "告": "gao",
  "诉": "su",
  "走": "zou",
  "京": "jing",
  "座": "zuo",
  "安": "an",
  "广": "guang",
  "场": "chang",
  "非": "fei",
  "宽": "kuan",
  "丽": "li",
  "洁": "jie",
  "认": "ren",
  "连": "lian",
  "选": "xuan",
  "圈": "quan",
  "涂": "tu",
  "填": "tian",
  "试": "shi",
  "练": "lian",
  "玩": "wan",
  "得": "de",
  "急": "ji",
  "直": "zhi",
  "哭": "ku",
  "跟": "gen",
  "忽": "hu",
  "然": "ran",
  "听": "ting",
  "喊": "han",
  "快": "kuai",
  "己": "ji",
  "背": "bei",
  "只": "zhi",
  "很": "hen",
  "孤": "gu",
  "单": "dan",
  "种": "zhong",
  "每": "mei",
  "都": "dou",
  "邻": "lin",
  "居": "ju",
  "叫": "jiao",
  "招": "zhao",
  "呼": "hu",
  "乐": "le",
  "怎": "zen",
  "独": "du",
  "跳": "tiao",
  "绳": "sheng",
  "当": "dang",
  "还": "hai",
  "羽": "yu",
  "球": "qiu",
  "劲": "jin",
  "轮": "lun",
  "排": "pai",
  "母": "mu",
  "页": "ye",
  "止": "zhi",
  "斤": "jin",
  "寸": "cun",
  "丁": "ding",
  "千": "qian",
  "全": "quan",
  "元": "yuan",
  "静": "jing",
  "思": "si",
  "床": "chuang",
  "疑": "yi",
  "举": "ju",
  "望": "wang",
  "低": "di",
  "故": "gu",
  "胆": "dan",
  "敢": "gan",
  "勇": "yong",
  "讲": "jiang",
  "窗": "chuang",
  "乱": "luan",
  "拉": "la",
  "样": "yang",
  "笑": "xiao",
  "再": "zai",
  "睡": "shui",
  "觉": "jue",
  "端": "duan",
  "粽": "zong",
  "节": "jie",
  "总": "zong",
  "煮": "zhu",
  "盼": "pan",
  "米": "mi",
  "枣": "zao",
  "甜": "tian",
  "分": "fen",
  "鲜": "xian",
  "肉": "rou",
  "了": "le",
  "册": "ce",
  "支": "zhi",
  "台": "tai",
  "电": "dian",
  "视": "shi",
  "部": "bu",
  "机": "ji",
  "衣": "yi",
  "裤": "ku",
  "物": "wu",
  "捉": "zhuo",
  "迷": "mi",
  "藏": "cang",
  "造": "zao",
  "蚂": "ma",
  "蚁": "yi",
  "运": "yun",
  "食": "shi",
  "粮": "liang",
  "房": "fang",
  "结": "jie",
  "网": "wang",
  "圆": "yuan",
  "严": "yan",
  "寒": "han",
  "酷": "ku",
  "暑": "shu",
  "暖": "nuan",
  "晨": "chen",
  "细": "xi",
  "朝": "chao",
  "霞": "xia",
  "夕": "xi",
  "杨": "yang",
  "香": "xiang",
  "操": "cao",
  "拔": "ba",
  "拍": "pai",
  "跑": "pao",
  "踢": "ti",
  "铃": "ling",
  "真": "zhen",
  "闹": "nao",
  "丢": "diu",
  "沙": "sha",
  "身": "shen",
  "体": "ti",
  "之": "zhi",
  "初": "chu",
  "相": "xiang",
  "近": "jin",
  "习": "xi",
  "远": "yuan",
  "教": "jiao",
  "道": "dao",
  "专": "zhuan",
  "幼": "you",
  "玉": "yu",
  "知": "zhi",
  "义": "yi",
  "饭": "fan",
  "饱": "bao",
  "茶": "cha",
  "泡": "pao",
  "轻": "qing",
  "穿": "chuan",
  "袍": "pao",
  "鞭": "bian",
  "炮": "pao",
  "诗": "shi",
  "首": "shou",
  "偷": "tou",
  "浮": "fu",
  "萍": "ping",
  "泉": "quan",
  "惜": "xi",
  "照": "zhao",
  "柔": "rou",
  "荷": "he",
  "露": "lu",
  "角": "jiao",
  "浪": "lang",
  "迈": "mai",
  "悄": "qiao",
  "泪": "lei",
  "次": "ci",
  "给": "gei",
  "壳": "ke",
  "虾": "xia",
  "装": "zhuang",
  "像": "xiang",
  "淘": "tao",
  "娃": "wa",
  "珠": "zhu",
  "摇": "yao",
  "篮": "lan",
  "亮": "liang",
  "晶": "jing",
  "停": "ting",
  "坪": "ping",
  "展": "zhan",
  "透": "tou",
  "翅": "chi",
  "膀": "bang",
  "朵": "duo",
  "要": "yao",
  "腰": "yao",
  "阴": "yin",
  "沉": "chen",
  "呀": "ya",
  "忙": "mang",
  "呢": "ne",
  "吗": "ma",
  "面": "mian",
  "空": "kong",
  "闷": "men",
  "吧": "ba",
  "消": "xiao",
  "息": "xi",
  "棍": "gun",
  "豆": "dou",
  "汤": "tang",
  "蚊": "wen",
  "扇": "shan",
  "椅": "yi",
  "牵": "qian",
  "织": "zhi",
  "斗": "dou",
  "具": "ju",
  "铅": "qian",
  "新": "xin",
  "平": "ping",
  "盒": "he",
  "些": "xie",
  "此": "ci",
  "仔": "zai",
  "检": "jian",
  "查": "cha",
  "所": "suo",
  "伙": "huo",
  "伴": "ban",
  "钟": "zhong",
  "迟": "chi",
  "灯": "deng",
  "等": "deng",
  "啊": "a",
  "决": "jue",
  "定": "ding",
  "已": "yi",
  "经": "jing",
  "位": "wei",
  "表": "biao",
  "虎": "hu",
  "熊": "xiong",
  "通": "tong",
  "注": "zhu",
  "意": "yi",
  "遍": "bian",
  "百": "bai",
  "为": "wei",
  "因": "yin",
  "舌": "she",
  "理": "li",
  "忘": "wang",
  "第": "di",
  "猴": "hou",
  "块": "kuai",
  "兴": "xing",
  "掰": "bai",
  "扛": "kang",
  "往": "wang",
  "棵": "ke",
  "满": "man",
  "扔": "reng",
  "摘": "zhai",
  "捧": "peng",
  "追": "zhui",
  "刷": "shua",
  "梳": "shu",
  "巾": "jin",
  "皂": "zao",
  "洗": "xi",
  "澡": "zao",
  "脸": "lian",
  "盆": "pen",
  "棉": "mian",
  "姑": "gu",
  "娘": "niang",
  "病": "bing",
  "她": "ta",
  "治": "zhi",
  "燕": "yan",
  "帮": "bang",
  "害": "hai",
  "别": "bie",
  "干": "gan",
  "惊": "jing",
  "奇": "qi",
  "咕": "gu",
  "咚": "dong",
  "熟": "shu",
  "掉": "diao",
  "湖": "hu",
  "吓": "xia",
  "啦": "la",
  "鹿": "lu",
  "象": "xiang",
  "野": "ye",
  "拦": "lan",
  "哪": "na",
  "那": "na",
  "领": "ling",
  "壁": "bi",
  "借": "jie",
  "咬": "yao",
  "难": "nan",
  "爬": "pa",
  "您": "nin",
  "拨": "bo",
  "赶": "gan",
  "摆": "bai",
  "过": "guo",
  "孩": "hai",
  "转": "zhuan",
  "吵": "chao",
  "现": "xian",
  "顶": "ding",
  "胖": "pang",
  "票": "piao",
  "户": "hu",
  "交": "jiao",
  "父": "fu"
};
